### ISSUE TITLE
Temporary Files

### ISSUE THREAD

**Issue by Saishy** [yahoo/express-busboy#13]
Do this delete temporary files uploaded or still suffer from http://andrewkelley.me/post/do-not-use-bodyparser-with-express-js.html ?

**Comment by davglass** [comment]
It does not, it's your job to delete the uploaded files. In the case of this module we allow uploads to only certain paths. That way your route handles the upload and it doesn't allow it from others. This greatly reduces the amount of places you need to check for uploaded files making it easy enough for you to clean up after it :)
