### ISSUE TITLE
Return before async callback is triggered

### ISSUE THREAD

**Issue by JoeChapman** [yahoo/express-busboy#14]
Is it possible that https://github.com/yahoo/express-busboy/blob/master/index.js#L43 will return to the calling function before the callback in the previous function is fired? Perhaps it would be safer to move the `return` statement into the callback?

**Comment by davglass** [comment]
No, that `return` is to just stop the processing of the rest of the method. The [`next`](https://github.com/yahoo/express-busboy/blob/master/index.js#L41) callback is the important one. The middleware won't continue until that is called, so the `return` there has no impact on the processing.
