### ISSUE TITLE
Saving to no dir

### ISSUE THREAD

**Issue by houssem-yahiaoui** [yahoo/express-busboy#15]
I want to know if we can make the upload happen but not to a dir in our application, since my needs are based on saving those files in a DB, so is it possible ?

**Comment by davglass** [comment]
Not out of the box since this module consumes the stream during the upload. What you would likely want to do is let this module write the file out to disk then post process it in your application code to pipe it into a DB and then delete it from the disk.

**Comment by houssem-yahiaoui** [comment]
Thank you @davglass for you fast prompt. already started doing that !
