### ISSUE TITLE
req.files always returning empty object

### ISSUE THREAD

**Issue by cinder92** [yahoo/express-busboy#19]
Hello i just read documentation and enabled upload files, i have this code

index.js

```
var express = require('express');
var bb = require('express-busboy');
var app = express();

bb.extend(app,{
	upload: true,
        path: '/uploads',
        allowedPath: /^\/uploads$/
});

app.post('/sendmail.html',require('./routes').sendmail)
```

routes.js

```
exports.sendmail = (req,res) => {
    console.log(req.files) // <-- always is {}
}
```

index.html

```
<form id="cform" name="cform" method="post" action="/sendmail.html" enctype="multipart/form-data">
    <input type="file" name="upload" />
</form>
```

any fix for this?

**Comment by cinder92** [comment]
when i just console.log(req) i saw this output, some advice?

```
opts: 
      { upload: true,
        immediate: false,
        path: '/var/folders/jh/5f_9xzv94zx4jqjr5kdc17h00000gn/T/express-busboy',
        headers: [Object] } },
```

**Comment by davglass** [comment]
Try this:

```js
bb.extend(app,{
	upload: true,
        path: '/uploads',
        allowedPath: /^\/sendmail.html$/
});
```

`allowedPath` needs to match the path the upload is being `POST`ed to.

**Comment by cinder92** [comment]
thanks for quick reply, but no, still getting empty files...

**Comment by cinder92** [comment]
my `uploads` folder is in root project, needs to be in another place?

**Comment by cinder92** [comment]
i'm testing in local server....

**Comment by davglass** [comment]
The `path` config needs to be the full directory path in which you want the files stored, try this.

```js
const path = require('path');
bb.extend(app,{
	upload: true,
        path: path.join(__dirname, 'uploads'),
        allowedPath: /^\/sendmail.html$/
});
```

**Comment by cinder92** [comment]
@davglass  thanks for your help, but still not working...

**Comment by davglass** [comment]
Can I get a copy of your test app? Maybe post it to a gist? Then I can debug it locally. But it should work.

**Comment by cinder92** [comment]
@davglass  i just editing your plugin, and seems not be entering to `req.busboy.on('file', (name, file, filename, encoding, mimetype)` on line 107, after that i can successfully out put data as `console.log('uploading files')` but not to `req.busboy.on('file')`, for copy of project yes of course, but its a big one code...

**Comment by cinder92** [comment]
@davglass  when i do `console.dir(req.headers['content-type'])` i see `'application/x-www-form-urlencoded'`  but my form has `enctype="multipart/form-data"`

**Comment by cinder92** [comment]
@davglass  i just test it with postman and everything is working, but it seems that my form is sending like method GET instead of POST, but my form was set correctly... so sad...

**Comment by cinder92** [comment]
@davglass  thanks for all your help, i just figured out, that React Js, was no setting enctype correctly to my form, thanks for your awesome plugin, keep working on it ;)

**Comment by davglass** [comment]
Awesome, glad it worked..
