### ISSUE TITLE
When POST filename="", it doesn't work as expected

### ISSUE THREAD

**Issue by czheo** [yahoo/express-busboy#2]
Usually, when you create a plain HTML form as
``` html
<form action="" method="post" enctype="multipart/form-data">
  <input type="file" name="image">
  <input type="submit" class="submit" value="submit" name="">
</form>
```
After clicking the submit button without assigning a file, a HTTP request with empty filename will be sent.
```
Content-Disposition: form-data; name="image"; filename=""
Content-Type: application/octet-stream
```
So, I think you should do some empty filename check in the `file` event callback.
https://github.com/yahoo/express-busboy/blob/master/index.js#L40-L56

**Comment by davglass** [comment]
Published in `express-busboy@2.5.0`

**Comment by BlaM** [comment]
Still does not work for me. The "finish" handler is never called.

    <form action="/upload" method="post" enctype="multipart/form-data">
    <input name="file" type="file"> <button type="submit">Upload</button>
    </form>

**Comment by BlaM** [comment]
This seems to be a busboy issue: https://github.com/mscdex/busboy/issues/95
