### ISSUE TITLE
Don't replace the original `body` of the request

### ISSUE THREAD

**Issue by th317erd** [yahoo/express-busboy#35]
I have a situation where I need to verify a webhook signature, which requires the original unparsed JSON body. Re-serializing the JSON isn't the best approach, as my JS engine may order the keys differently, or little things like whitespace might change, which would cause the signature validation to fail.

I am going to open a PR to fill this need. I considered the best way to achieve this for a while, including adding an extra option, but I feel it is probably best (and harmless) to pre-assign the `req.body` to a `req.rawBody` and call it a day.

Thoughts?

PR: https://github.com/yahoo/express-busboy/pull/36

**Comment by redonkulus** [comment]
Fixed with #41
